# Generated by Django 4.1 on 2022-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='Unknown', unique=True)),
                ('type', models.CharField(default='Unknown', max_length=6)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('continent_code', models.CharField(default='Unknown', max_length=2)),
                ('continent_name', models.CharField(default='Unknown', max_length=20)),
                ('country_code', models.CharField(default='Unknown', max_length=10)),
                ('country_name', models.CharField(default='Unknown', max_length=70)),
                ('region_code', models.CharField(default='Unknown', max_length=10)),
                ('region_name', models.CharField(default='Unknown', max_length=50)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('zip', models.CharField(default='Unknown', max_length=10)),
            ],
        ),
    ]
