# Generated by Django 4.1 on 2022-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='type',
            field=models.CharField(default='Unknow', max_length=6),
        ),
    ]
