# Generated by Django 4.1 on 2022-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_alter_locations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='continent_code',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
