# Generated by Django 4.1 on 2022-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0003_alter_locations_continent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='type',
            field=models.CharField(max_length=6),
        ),
    ]
